//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demogsoft1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.ModelConfiguration.Conventions;

    public partial class gsoftDBEntities : DbContext
    {
        public gsoftDBEntities()
            : base("name=gsoftDBEntities")
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
         
            throw new UnintentionalCodeFirstException();
        }
       
    
        public virtual DbSet<mstAccount> mstAccounts { get; set; }
        public virtual DbSet<mstBrand> mstBrands { get; set; }
        public virtual DbSet<mstBsgrGroup> mstBsgrGroups { get; set; }
        public virtual DbSet<mstCompany> mstCompanies { get; set; }
        public virtual DbSet<mstDepartment> mstDepartments { get; set; }
        public virtual DbSet<mstItem> mstItems { get; set; }
        public virtual DbSet<mstProduct> mstProducts { get; set; }
        public virtual DbSet<mstState> mstStates { get; set; }
        public virtual DbSet<mstTax> mstTaxes { get; set; }
        public virtual DbSet<trnPurchase> trnPurchases { get; set; }
        public virtual DbSet<trnPurchaseItem> trnPurchaseItems { get; set; }
        public virtual DbSet<trnSale> trnSales { get; set; }
        public virtual DbSet<trnSalesItem> trnSalesItems { get; set; }
     
    }
}
