//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demogsoft1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mstAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstAccount()
        {
            this.trnPurchases = new HashSet<trnPurchase>();
            this.trnSales = new HashSet<trnSale>();
        }
    
        public int AccountId { get; set; }
        public string AccountName { get; set; }
        public string ShortName { get; set; }
        public string Address_ { get; set; }
        public string CityName { get; set; }
        [StringLength(8, MinimumLength = 6)]
        [Required(ErrorMessage = "Pin Code is Required and must be of 6-8 number")]
        public string PinCode { get; set; }
        [Required(ErrorMessage = "Required")]
        [RegularExpression(@"^(\d{10})$", ErrorMessage = "Wrong mobile it must be of 10 digit")]
        public string Mobile { get; set; }
        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Required GST Number.")]
        [RegularExpression(@"^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$", ErrorMessage = "Invalid GST Number.")]
        public string GSTNo { get; set; } //06BZAHM6385P6Z2
        [Required(ErrorMessage = "PAN Number is required")]
        [RegularExpression("^([A-Za-z]){5}([0-9]){4}([A-Za-z]){1}$", ErrorMessage = "Invalid PAN Number")]
        public string PANNo { get; set; }
        [DefaultValue(true)]
        public bool IsActive { get; set; }
        public Nullable<int> BsgrId { get; set; }
        public int StateId { get; set; }
    
        public virtual mstBsgrGroup mstBsgrGroup { get; set; }
        public virtual mstState mstState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnPurchase> trnPurchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnSale> trnSales { get; set; }
    }
}
