//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demogsoft1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mstCompany
    {
        public int CompanyId { get; set; }
        [Required]
        public string CompanyName { get; set; }
        [DefaultValue(true)]
        public bool IsActive { get; set; }
        [Required]
        public int StateId { get; set; }
    
        public virtual mstState mstState { get; set; }
    }
}
