//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demogsoft1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class mstItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstItem()
        {
            this.trnPurchaseItems = new HashSet<trnPurchaseItem>();
            this.trnSalesItems = new HashSet<trnSalesItem>();
        }
    
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string ShortName { get; set; }
        public Nullable<decimal> DiscountPrc { get; set; }
        public Nullable<System.DateTime> DiscountFromDate { get; set; }
        public Nullable<System.DateTime> DiscountToDate { get; set; }
        [DefaultValue(0)]
        public int DefaultQty { get; set; }
        [DefaultValue(true)]
        public bool IsActive { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> TaxId { get; set; }
    
        public virtual mstBrand mstBrand { get; set; }
        public virtual mstDepartment mstDepartment { get; set; }
        public virtual mstProduct mstProduct { get; set; }
        public virtual mstTax mstTax { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnPurchaseItem> trnPurchaseItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnSalesItem> trnSalesItems { get; set; }
    }
}
