//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demogsoft1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class mstTax
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstTax()
        {
            this.mstItems = new HashSet<mstItem>();
            this.trnPurchaseItems = new HashSet<trnPurchaseItem>();
            this.trnSalesItems = new HashSet<trnSalesItem>();
        }
    
        public int TaxId { get; set; }
        [Required]
        public string TaxName { get; set; }
        [Required]
        public decimal TaxPrc { get; set; }
        public decimal SGSTPrc { get; set; }
        public decimal CGSTPrc { get; set; }
        public decimal IGSTPrc { get; set; }
        [DefaultValue(true)]
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstItem> mstItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnPurchaseItem> trnPurchaseItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trnSalesItem> trnSalesItems { get; set; }
    }
}
