//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demogsoft1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class trnPurchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trnPurchase()
        {
            this.trnPurchaseItems = new List<trnPurchaseItem>();
        }
    
        public int PurchaseId { get; set; }
        [Required]
        public string PurchaseType { get; set; }
        [Required]
        public string VoucherNo { get; set; }
        [Required]
        public System.DateTime VoucherDate { get; set; }
        [Required]
        public string InvoiceType { get; set; }
        public decimal TotalAmount { get; set; }
        public string Remarks { get; set; }
        [Required]
        public int AccountId { get; set; }
      
        public virtual mstAccount mstAccount { get; set; }

     //   [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<trnPurchaseItem> trnPurchaseItems { get; set; }

    }
}
