//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demogsoft1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class trnSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trnSale()
        {
            this.trnSalesItems = new List<trnSalesItem>();
        }
    
        public int SalesId { get; set; }
        [Required]
        public string SalesType { get; set; }
        [Required]
        public string VoucherNo { get; set; }
        [Required]
        public System.DateTime VoucherDate { get; set; }
        [Required]
        public string InvoiceType { get; set; }
        public decimal NetAmt { get; set; }
        public string Remarks { get; set; }
        [Required]
        public int AccountId { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
    
        public virtual mstAccount mstAccount { get; set; }
      //  [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<trnSalesItem> trnSalesItems { get; set; }
    }
}
